name: Azure Pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select the environment'
        options:
          - development

permissions:
      id-token: write
      contents: read
jobs: 
  terraform-exec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Change working directory
        run: cd environments/${{ github.event.inputs.environment }}

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply --auto-approve
